# Generated by Django 4.1.3 on 2023-03-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_alter_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='picture_url',
            field=models.URLField(blank=True, default='http://buprof.com/wp-content/uploads/2016/01/konular.png'),
        ),
    ]
