# Generated by Django 4.1.3 on 2023-03-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_topic_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
