# Generated by Django 4.1.3 on 2023-03-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_operator_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
    ]
