# Generated by Django 5.2.9 on 2026-01-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(default='static/images/default_user.jpg', upload_to=''),
        ),
    ]
