# Generated by Django 4.1.3 on 2023-02-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productpictures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPictures',
            new_name='ProductPicture',
        ),
    ]
