# Generated by Django 4.1.3 on 2023-02-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_europe_delivery_product_europe_out_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='europe_delivery',
            field=models.IntegerField(default=7),
        ),
    ]
