# Generated by Django 4.1.3 on 2023-02-18 16:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_alter_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ProductReview',
        ),
    ]
