# Generated by Django 4.1.3 on 2023-02-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_review_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='stars_given',
        ),
        migrations.AddField(
            model_name='product',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
