# Generated by Django 4.1.3 on 2023-02-18 19:59

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productreview_stars_given_product_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productreview',
            name='stars_given',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
