# Generated by Django 4.1.3 on 2023-02-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productreview_created_at_productreview_stars_given'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
