# Generated by Django 4.1.3 on 2023-03-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_sold_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categories',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
