# Generated by Django 4.1.3 on 2023-03-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_category_categories_alter_category_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='picture',
            new_name='icon',
        ),
    ]
