# Generated by Django 4.1.3 on 2023-03-04 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_companynews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companynews',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='companynews',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
