# Generated by Django 4.1.3 on 2023-03-04 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_companynews_options_companynews_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
