# Generated by Django 4.1.3 on 2023-03-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_companynews_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companynews',
            name='deleted_in',
            field=models.IntegerField(blank=True, default=7),
        ),
    ]
