# Generated by Django 4.1.3 on 2023-03-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_companynews_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE'), ('X', 'ALL')], default='X', max_length=1),
        ),
    ]
