# Generated by Django 4.1.3 on 2023-03-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_company_alter_product_europe_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('MEN MAN', 'MALE'), ('WOMEN WOMAN', 'FEMALE'), ('X', 'ALL')], default='X', max_length=20),
        ),
    ]
