# Generated by Django 4.1.3 on 2023-03-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='local',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
