# Generated by Django 4.1.3 on 2023-03-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_product_gender_remove_product_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
