# Generated by Django 4.1.3 on 2023-03-08 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_localproduct_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpicture',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='local_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.localproduct'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
