# Generated by Django 4.1.3 on 2023-03-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_remove_productpicture_local_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpicture',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
