# Generated by Django 4.1.3 on 2023-03-24 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='discount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', unique=True),
        ),
    ]
